# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Véritable Générateur Aléatoire
email: verigeneale@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Site para minhas coisas aleatórias. Principalmente sobre TI, porém também
  possivelmente sobre outras coisas como vida, trabalho, café, meditação,
  línguas, kung-fu, anatomia, desenho, jogos, modelagem, matemática... 
  Realmente aleatório...
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://fabionitto.github.io" # the base hostname & protocol for your site
twitter_username: fabionitto 
github_username:  fabionitto

# Build settings
markdown: kramdown
